### ISSUE TITLE
Installing in a Conda environment

### ISSUE THREAD

**Issue by gkaf89** [satijalab/seurat-wrappers#183]
When installing this package collection in a Conda environment, I noticed that it depends on the R package [`R.utils`](https://cran.r-project.org/web/packages/R.utils/index.html) and on a few other libraries.

This is the  specification of the Conda environment I use to install the required libraries:
```yaml
name: R
channels:
- conda-forge
dependencies:
- conda-forge::glpk
- conda-forge::libxml2
- conda-forge::openssl
- conda-forge::r-base
- conda-forge::r-packrat
```

It would be useful if this information was available in the installation instructions.
